name = "Arena"
uuid = "53eacc40-fba4-5ad6-b4bb-526e51630e63"
desc = "Visualization tools for Caesar.jl related SLAM solutions"
version = "0.3.0"

[deps]
Caesar = "62eebf14-49bc-5f46-9df9-f7b7ef379406"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Manifolds = "1cead3c2-87b3-11e9-0ccd-23c62b72b94e"
TensorCast = "02d47bb6-7ce6-556a-be16-bb1710789e2b"

[compat]
Caesar = "0.14"
ColorSchemes = "3"
DocStringExtensions = "0.8, 0.9"
GLMakie = "0.7, 0.8"
Manifolds = "0.8.15"
TensorCast = "0.4"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
