name = "Arena"
uuid = "53eacc40-fba4-5ad6-b4bb-526e51630e63"
desc = "Visualization tools for Caesar.jl related SLAM solutions"
version = "0.3.0"

[deps]
Caesar = "62eebf14-49bc-5f46-9df9-f7b7ef379406"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[compat]
DocStringExtensions = "0.8, 0.9"
Caesar = "0.13, 0.14"
GLMakie = "0.7"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
